# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_pattern_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='num_docs',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
